// "use client"

import RequireAuth from "../lib/ReuquireAuth"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
    <RequireAuth>
    {children}
    </RequireAuth>
    </>
  )
}
