// "use client"
import { ReduxProvider } from '../redux/providers'
import StyledComponentsRegistry from '../lib/register'
import GlobalThemeWrapper from '../lib/GlobalThemeWrapper'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      {/* <body> */}
        <ReduxProvider>
        <StyledComponentsRegistry>
          <GlobalThemeWrapper>
          {children}
          </GlobalThemeWrapper>
        </StyledComponentsRegistry>
        </ReduxProvider>
      {/* </body> */}
    </>
  )
}
